export type BuildId = 'wolf' | 'lady';
export type GodId = 'wolf' | 'lady' | 'angels' | 'dust';
export interface Gift { id:string; name:string; god:GodId; devotion:number; energy:number; stat:string; condition:string; purpose:string; caution:string; source:string }
export interface Task { id:string; text:string }
export interface Stage { id:string; title:string; region:string; direction:string; tasks:Task[]; gifts:string[]; gear:string; gate?:string; hint?:string; spoiler?:boolean; source:string }
export const gods:Record<GodId,{name:string;stat:string;short:string}> = {
  wolf:{name:'The Great Forest Wolf',stat:'Strength',short:'Wolf'},
  lady:{name:'Our Lady of the Sanguine Moon',stat:'Perception',short:'Lady'},
  angels:{name:'The Blind Angels',stat:'Endurance',short:'Angels'},
  dust:{name:'The Lords of Dust',stat:'Intellect',short:'Dust'}
};
const g=(id:string,name:string,god:GodId,devotion:number,energy:number,stat:string,condition:string,purpose:string,caution:string,source='skill_tree.lua:37–83; actions.lua') : Gift => ({id,name,god,devotion,energy,stat,condition,purpose,caution,source});
export const gifts:Record<BuildId,Gift[]> = {
 wolf:[
 g('slam','Slam','wolf',2,40,'STR 5','Wintersholl besuchen: +2 Wolf-Punkte. Die erste freie Tear für Angels sparen; Wintersholl allein bezahlt Slam.','Schiebt einen Gegner weg. Gegen eine Wand oder ein Hindernis gerichtet wird der Abstand besonders wertvoll.','Zuerst eine sichere Stellung suchen; kein endloser Slam-Loop nötig.'),
 g('hurl','Hurl','wolf',2,50,'STR 10','Weitere 2 Wolf-Punkte: z. B. fünf Hirsche erlegen (+2). Crossbow ist ab Slam / STR 5 eine Jagdhilfe vor Hurl; die Aufgabe darf warten.','Wirft die ausgerüstete Nahkampfwaffe als Fernangriff. Kostet keine Pfeile und öffnet die Sword-Schwelle.','Eine Nahkampfwaffe muss ausgerüstet sein. Hurl + Feast kosten neutral zusammen 110 Energie.','actions.lua:3730–3767'),
 g('lifesight','Lifesight','angels',1,30,'END 5','Hearthaven besuchen: +2 Angels-Punkte; nach dem Kauf bleibt einer übrig.','Zeigt Lebewesen hinter Sichthindernissen. Der END-Zuwachs hilft bei der Ausrüstungslast.','Ein Erkundungswerkzeug, kein Schadenszauber.'),
 g('feast','Feast','lady',2,60,'PER 5','The Red Grove besuchen: +2 Lady-Punkte bezahlen den Kauf.','Heilt durch einen Angriff auf einen geeigneten benachbarten Gegner.','Heilung kann bei Resistenz, Block oder Immunität ausbleiben. Heilt Gesundheit, nicht Hunger.','actions.lua:4993–5047; main.lua:89–90'),
 g('blind-leap','Blind Leap','angels',2,40,'END 10','Insgesamt 3 Angels-Punkte. Alle fünf Gottstädte besuchen gibt weitere +2.','Versetzt dich auf ein freies, sichtbares und zu Fuß erreichbares Feld.','Macht dich selbst blind. Lifesight vorher lernen; kein Sprung durch geschlossene Wände.','actions.lua:5230–5250'),
 g('revelation','Revelation','dust',1,30,'INT 5','Barrow-Linn besuchen: +2 Dust-Punkte, davon einen ausgeben.','Prüft Fallen und verborgene Türen. Besonders hilfreich vor langen Dungeons.','Die Gabe ersetzt keine Kampfvorbereitung.'),
 g('hallow','Hallow','wolf',2,40,'STR 15','Weitere 2 freie Wolf-Punkte oder Erkundungstränen. Erst nach tatsächlichem Verdienst kaufen.','Weiht den Bereich einer Leiche oder von Knochen. Dort verfehlen normale Nahkampfschläge nicht und verursachen ×1,5 Schaden.','Braucht Leiche/Knochen. Erst nach dem ersten geeigneten Kill benutzen.','actions.lua:3817–3872; 6865–6871'),
 g('retribution','Retribution','angels',2,80,'END 15','Insgesamt 5 Angels-Punkte. Ortsbesuche geben 4; eine Tear ergänzt den fehlenden Punkt. Alternativ später 100 Untote (+2).','Schützt gegen einen Treffer innerhalb eines begrenzten Zeitfensters und wirft Schaden zurück.','Nach dem Treffer verbraucht. END 15 erhöht den reflektierten Anteil gegenüber END 5 noch nicht. 80 Energie bewusst reservieren.','actions.lua:5221; actor.lua'),
 g('howl','Howl','wolf',5,120,'STR 20','Nach Garden of Lorelei: Lightning-bolt Amulet anlegen und max. Energie ≥120 prüfen. Zusätzlich 5 freie Wolf-Punkte.','Ruft einen spektralen Wolf für schwierige Begegnungen.','Bei genau 120 Energie bleibt nach der Beschwörung 0. Nicht sofort eine weitere Gabe einplanen.','actions.lua:4122; treasure_sets.lua:773–779'),
 g('shockwave','Shockwave','wolf',2,60,'STR 25','Später weitere 2 Wolf-Punkte, z. B. aus natürlich erreichten Kampf-/Fundaufgaben.','Sprung mit Flächenschaden für größere Gruppen.','Kann deinen Wolf und andere Verbündete treffen. Normaler Sword-Angriff bleibt der Standard.','actions.lua:3783–3810')
 ],
 lady:[
 g('gash','Gash','lady',1,50,'PER 5','Erste Devotional Tear vom Priest of Balance der Lady zuordnen.','Nahbereichsangriff mit Blutverlust und Chance auf Phials of Blood. Der Kauf ermöglicht Shortbow.','Gash ist kein Fernschuss. Blutphials sind bei niedriger PER nicht garantiert.','actions.lua:4960–4987'),
 g('feast','Feast','lady',2,60,'PER 10','The Red Grove besuchen: +2 Lady-Punkte.','Heilt beim Angriff auf einen geeigneten benachbarten Gegner. Der Kauf ermöglicht Longbow.','Kann ohne Heilung enden. Gash + Feast kosten neutral 110 Energie; keine automatische Zweierkombo.','actions.lua:4993–5047'),
 g('lifesight','Lifesight','angels',1,30,'END 5','Hearthaven besuchen: +2 Angels-Punkte.','Findet Lebewesen hinter Hindernissen. Erhöht Tragfähigkeit und ermöglicht die Mace als Reserve.','Nicht alle möglichen Ziele sind dadurch schon sicher erreichbar.'),
 g('drill-shot','Drill Shot','lady',2,40,'PER 15','Weitere 2 Lady-Punkte: 25 Wildkräuter finden (+2) oder zwei tatsächlich gewonnene Erkundungstränen.','Schießt durch Körper und Stein. Gegner in einer Linie oder hinter Hindernissen sind gute Ziele.','Ausgerüstete Fernwaffe und eine passende Munition nötig. Nicht jedes normale Einzelziel braucht diese Gabe.','actions.lua:5049–5096'),
 g('blind-leap','Blind Leap','angels',2,40,'END 10','Insgesamt 3 Angels-Punkte; alle fünf Gottstädte besuchen liefert weitere +2.','Schafft Abstand auf einem sichtbaren, freien, begehbaren Feld.','Eigene Blindheit beachten. Lifesight vorher lernen.','actions.lua:5230–5250'),
 g('revelation','Revelation','dust',1,30,'INT 5','Barrow-Linn besuchen: +2 Dust-Punkte.','Deckt Fallen und verborgene Türen auf.','Erst Drill Shot und Blind Leap in dieser Kaufreihenfolge abschließen.'),
 g('moonlight','Moonlight','lady',5,120,'PER 20','Nach Garden of Lorelei: Lightning-bolt Amulet anlegen, max. Energie ≥120 und 5 freie Lady-Punkte prüfen.','Beschwört einen Helfer, während du mit dem Bogen aus Abstand weiterkämpfst.','Bei genau 120 Energie ist die Leiste anschließend leer. Energiebedarf für Heilung und Flucht berücksichtigen.','actions.lua:5198–5218; treasure_sets.lua:773–779'),
 g('retribution','Retribution','angels',2,80,'END 15','Insgesamt 5 Angels-Punkte: Ortsaufgaben plus eine Tear oder später 100 Untote.','Schutz gegen einen Treffer innerhalb eines begrenzten Zeitfensters, wenn der Abstand zusammenbricht.','Nach einem Treffer verbraucht. Teure Absicherung; normales Schießen und Positionieren tragen den Build.','actions.lua:5221'),
 g('star-shot','Star Shot','lady',3,60,'PER 25','Später 3 weitere Lady-Punkte; Fernkampf-, Kräuter- und Reliktaufgaben nutzen.','Kreisförmige Salve: acht Geschosse, jeweils doppelter normaler Schussschaden.','Braucht Fernwaffe und 8 passende Munition. Für Gruppen aufheben.','actions.lua:5099–5140')
 ]
};
export const builds:Record<BuildId,{name:string;subtitle:string;description:string;pros:string[];cons:string[];loop:string[];stats:string;funding:string}> = {
 wolf:{name:'Wolf & Schild',subtitle:'Nahkampf · Kontrolle · Begleiter',description:'Die Empfehlung für den ersten Durchlauf. Eine Einhandwaffe und ein Schild tragen den Kampf; Gaben schaffen Abstand, heilen bei Gelegenheit und bringen später einen Helfer.',pros:['Einfache Grundroutine: Einzelgegner, normale Schläge, gezielte Kontrolle.','Hurl gibt einen Fernangriff ohne Munitionskosten.','Hallow belohnt einen gut gewählten Kampfplatz.'],cons:['Du stehst häufiger im Nahkampf und musst Poise im Blick behalten.','Feast hilft gegen Maschinen und andere ungeeignete Ziele nicht zuverlässig.','Der Wolf kommt erst nach ausreichender Energiekapazität und Devotion.'],loop:['Einzelnen Gegner an einen Engpass locken; mit normalen Schlägen oder Hurl beginnen.','Wenn er zu nah kommt: Slam Richtung Hindernis. Bei passender Leiche Hallow und auf dem geweihten Boden kämpfen.','Bei echtem Heilbedarf und geeignetem Ziel Feast. Für Rückzug Blind Leap mit der anschließenden Blindheit einplanen.','Später Howl vor schwierigen Begegnungen; danach Energievorrat für weitere Gaben prüfen. Shockwave von Verbündeten fernhalten.'],stats:'STR 25 · END 15 · PER 5 · INT 5 · FIN 0',funding:'21 Devotion: Wolf 13 · Angels 5 · Lady 2 · Dust 1. Aufgabenpunkte sind an ihren Gott gebunden; Tears sind frei zuordenbar.'},
 lady:{name:'Lady & Bogen',subtitle:'Fernkampf · Blutheilung · Durchschüsse',description:'Für dich, wenn du lieber Abstand hältst. Perception öffnet früh die Bögen; Lifesight und Drill Shot helfen gegen verdeckte Gegner. Heilung und Positionswechsel sichern Nahkontakt ab.',pros:['Viele Kämpfe lassen sich aus sicherem Abstand eröffnen.','Lifesight + Drill Shot helfen bei Hindernissen und Gegnerlinien.','Feast und später Moonlight geben zusätzliche Sicherheitswerkzeuge.'],cons:['Pfeile kosten Geld; Munition vor jeder Expedition prüfen.','Gash und Feast erfordern trotzdem kontrollierten Nahkontakt.','Etwas mehr Ziel- und Energieplanung; Blutheilung ist kein Universalheilmittel.'],loop:['Rückzugsfelder sichern und normale Bogenschüsse als Standard benutzen.','Bei verdeckten Zielen Lifesight; Drill Shot für lohnende Hindernisse oder Gegnerlinien.','Gash nur bei kontrolliertem Nahkontakt. Feast bei Heilbedarf an geeignetem Ziel; sonst mit Blind Leap Abstand schaffen.','Später Moonlight vor schweren Begegnungen. Star Shot für mehrere sinnvoll verteilte Gegner und mindestens 8 Munition.'],stats:'PER 25 · END 15 · INT 5 · STR 0 · FIN 0',funding:'19 Devotion: Lady 13 · Angels 5 · Dust 1. Lady-Punkte aus Ortsbesuch, Kräutern, Fernkampf und später der Crimson Candle; Tears füllen Lücken.'}
};
// Explicit task IDs keep saved checkmarks attached to tasks moved along the route.
const s=(id:string,title:string,region:string,direction:string,texts:(string|Task)[],giftIds:string[],gear:string,source:string,gate?:string,hint?:string,spoiler=false):Stage=>({id,title,region,direction,tasks:texts.map((text,i)=>typeof text==='string'?{id:`${id}-${i}`,text}:text),gifts:giftIds,gear,source,gate,hint,spoiler});
const hearthavenLore:Task = {id:'hearth-hidden-library',text:'Die unsichtbare / falsche Wand in Hearthaven finden und den verborgenen Bereich erkunden. Hinter der ersten Wand folgen mehrere weitere unsichtbare Wände: auch dort nach Durchgängen suchen und alle Räume durchstöbern. Dahinter warten zahlreiche Bücher mit reichlich Lore zur Welt, den Göttern und Calderas Geschichte. Die Bücher und Regale untersuchen und lesen.'};
const stoneInquiry:Task[] = [
 {id:'yarrow-stone-hint',text:'Nach der Höhle mit dem Bewohner in Yarrow über den Black Eyed Stone sprechen. Er liest die Inschrift; nach Serpent\'s Eye fragen und seinem Hinweis auf die Priester in Moon-upon-Thoss folgen. Den Stein mitnehmen.'},
 {id:'prepare-1',text:'Jetzt nach Moon-upon-Thoss: Mit Black Eyed Stone beim Priest of Balance nach Serpent\'s Eye → predecessor → Ruined Quarter fragen. Erst durch diese Antworten erfährst du den Namen Nevin und seinen Aufenthaltsort. Danach im nordwestlichen Ruinenviertel suchen und Nevin sagen. Seinen Antworten folgen: knew → truths → Serpents → hope → moons. Erst wenn er Roche erwähnt, nach Roche fragen; den Hinweis auf Barrow-Linn für den späteren Stadtbesuch notieren.'}
];
export function getStages(build:BuildId):Stage[]{
const w=build==='wolf';
return [
s('yarrow','Yarrow','Ankommen','Im Startdorf das südliche verfallene Gebäude und das Farmhaus durchsuchen; danach auf der Straße südwestwärts zur Hauptstadt.',[
 'Im verfallenen Gebäude die Käfer besiegen, Carems Notiz lesen und Tiny Key nehmen.',
 'Im Farmhaus die falsche Wand finden; die verschlossene Truhe öffnen und Graveyard Key nehmen.'
],[],'Graveyard Key behalten. Noch keinen großen Kauf erzwingen. Mit Startausrüstung einzelne Gegner bekämpfen und Rückzug lernen.','YarrowTriggers.csv:6–8,17–18,22,30,36; world_data.lua:87; dungeon_data.lua:664–707; research-cemetery.md','Anfängerfalle: Die Höhle hinter dem Familienfriedhof vorerst auslassen. Der Eingang erlaubt keinen einfachen Rückweg; zum Verlassen brauchst du den Dungeon-Schlüssel. Nach ein bis zwei frühen Gottfertigkeiten zurückkehren: in dieser Route bereits in Etappe 3. Mit Startausrüstung direkt hineinzugehen kann schnell tödlich enden.'),
s('capital','Moon-upon-Thoss','Ankommen','Von Yarrow auf der Straße südwestwärts zur Hauptstadt. Im Osten liegt die Street of the Gods.',[
 'Priest of Balance ansprechen: Dreamless → become Archon → Relics → simple. Die kostenlose Devotional Tear erhalten.',
 'Bei jedem der fünf anderen Priester nach relic fragen. Die Reliktaufgabe und Ortsnamen notieren.',
 w?'Die erste Tear für Angels sparen: Sie schließt später die Lücke zu Retribution. Slam wird über Wintersholl bezahlt.':'Die erste Tear der Lady zuordnen und Gash als erste Gabe kaufen.'
],w?[]:['gash'],w?'Heilreserve zuerst. Buckler nur bei Restgold (Basis 100); Dagger, Cap, Cotton Tunic und Leggings behalten. Shortsword erst mit STR 5.':'Shortbow beim Weaponsmith: PER 5, Basis 1.000. Pfeile und Heiltränke zuerst einplanen.','DialogueData.csv:31–38,72,86,97–98,111–112,126–127'),
...(w?[
s('winter','Wintersholl','Städtereise','Von der Hauptstadt zurück in Richtung Yarrow, dann ostwärts über die Straßen nach Wintersholl. Nach der Yarrow-Höhle mit dem Stein zur Hauptstadt zurückkehren.',[
 'Wintersholl besuchen: +2 Wolf-Devotion. Slam kaufen, damit STR 5 erreichen.',
 'Priester: Garden → not far → the beast → hunting grounds. Die Ziele markieren lassen.',
 'Klagenden Bewohner: disgrace → rogue guardian → history → weapon → pirates → coast.',
 {id:'winter-3',text:'Fünf Hirsche sind ein später nachholbares Wolf-Ziel (+2 Punkte), keine Voraussetzung zum Weiterreisen. Laufen sie dir weg, nicht im Nahkampf hinterherjagen: erst eine tragbare Fernwaffe besorgen oder die Jagd verschieben. Hurl mit 2 freien Wolf-Punkten lernen; für die Yarrow-Höhle nicht darauf warten.'},
 {id:'winter-ranged-option',text:'Frühe Jagdhilfe bei Bedarf: Crossbow beim Weaponsmith in Wintersholl oder der Hauptstadt (Basis 1.000) plus Bolts kaufen. Slam / STR 5 genügt; Shortbow braucht PER 5 und kommt im Plan erst nach Feast. Leichtes Jagdset: Shortsword + Cap + Cotton Tunic + Leggings + Crossbow = 36 / 40, Buckler dabei ablegen. Beide Waffen zählen zur Last. Nur kaufen, wenn danach Versorgungsgold bleibt; sonst weiterreisen und später zurückkommen.'},
 {id:'prepare-cemetery-check',text:'Für die frühe Rückkehr nach Yarrow reicht als Orientierung zunächst Slam (STR 5) mit Shortsword oder vergleichbarer Waffe. Hurl kann als zweite Gabe helfen, ist hier keine Pflicht. Leichte Startausrüstung und gegebenenfalls Buckler behalten; Gesundheit, Poise, Energie und Heilreserve auffüllen.'},
 {id:'yarrow-2',text:'Jetzt zurück nach Yarrow: Mit Graveyard Key zum Familienfriedhof nördlich der Farm und die Höhle abschließen. Gegner einzeln bekämpfen und bei sinkender Poise Abstand nehmen. Master Key und Black Eyed Stone aus der Haupttruhe nehmen, dann hinaus. Den Stein behalten und seine Inschrift erfragen.'},
 ...stoneInquiry
],['slam','hurl'],'Nach Slam: Shortsword ab STR 5 (1.000), mit Startkleidung + Buckler 30 / 40. Bei Jagdbedarf Crossbow (1.000) + Bolts statt weiterer Rüstung einplanen; mit Shortsword und Startkleidung ohne Buckler 36 / 40. Mit Hurl / STR 10 und genug Restgold direkt Sword (2.000) kaufen und Shortsword auslassen. Versorgung zuerst.','DialogueData.csv:51–59,131–148,198–220,422–425; achievements.lua:7–13; research-cemetery.md','Die Höhle ist ein früher Dungeon: ein bis zwei Gaben sind unsere Orientierung, keine feste Mindestanforderung. Für den Versuch weder Sword/STR 10 noch Lifesight/END 5 abwarten. Der Eingang bleibt bis zum Master Key gesperrt. Hurl erst mit 2 freien Wolf-Punkten; der Besuch bezahlt nur Slam. Hirschjagd und Fernwaffenkauf dürfen warten. Falls Hurl noch fehlt, darfst du Lifesight in Hearthaven und Feast in Red Grove vorziehen; ihre Ortsbesuche bezahlen die Gaben. Danach ist Shortbow für die spätere Jagd anlegbar.'),
s('hearth','Hearthaven','Städtereise','Nach der Hauptstadtspur zum Stein über die Straßen nordwärts ins Gebirge nach Hearthaven.',[
 'Hearthaven besuchen: +2 Angels-Devotion. Lifesight ist der geplante dritte Kauf. Wartet Hurl noch auf die Hirschjagd, Lifesight trotzdem jetzt lernen: END 5 hilft bei der Last.',
 'Priest of the Blind Angels: Relic → Tower of Veils → no way in.',
 'Die Spur red cloak notieren; bei der nächsten Rückkehr nach Wintersholl mit Bewohnern darüber sprechen. Die Spur führt nach Harrowdus.',
 hearthavenLore
],['lifesight'],'Nach Lifesight nicht das ganze Lederset kaufen. Erst bei Restgold Leather Armour statt Cotton Tunic (800): mit Sword + Starthelm/-beinen + Buckler Last 39 / 50,71. Optionale Gloves: 41. Cap und Leggings zunächst behalten.','DialogueData.csv:175–177,210–211; ObjectData.csv; HearthavenTriggers.csv; strings.lua:138–159; research-secrets.md'),
s('red','The Red Grove','Städtereise','Von Hearthaven zurück über die Straßen Richtung Westen/Südwesten nach The Red Grove.',[
 'The Red Grove besuchen: +2 Lady-Punkte. Feast ist der geplante vierte Kauf. Falls Hurl noch fehlt, Feast vorziehen: PER 5 macht Shortbow für die spätere Jagd anlegbar.',
 'Von einem Bewohner Blood is all erfahren und dies der Handmaiden sagen.',
 'Handmaiden: Candle → Necropolis → brave its tombs → not enough → solvent → Endera. Fünf Endera Herbs als späteres Ziel notieren.'
],['feast'],'Nach Feast / PER 5 ist Shortbow beim Weaponsmith in Red Grove oder der Hauptstadt anlegbar (Basis 1.000 + Arrows, Last 10). Für die aufgeschobene Hirschjagd jetzt erwägen. Mit Shortsword + Startkleidung + Buckler 40 / 50,71 bei END 5; mit Sword 42. Eine vorhandene Crossbow weiter benutzen oder ersetzen; nicht beide kaufen müssen. Heilung und Oil zuerst. Oil heilt Rot, bietet keine vorbeugende Immunität.','DialogueData.csv:363–380; speech_area.lua:18')
]:[
s('red','The Red Grove','Städtereise','Von Moon-upon-Thoss auf den westlichen Straßen nordwestwärts nach The Red Grove. Danach über Yarrow und die Friedhofshöhle mit dem Stein zur Hauptstadt zurückkehren.',[
 'Besuch gibt +2 Lady-Devotion. Feast als zweiten Kauf lernen: PER 10 erreichen.',
 'Bewohner nach Blood is all fragen und dies der Handmaiden sagen.',
 'Handmaiden: Candle → Necropolis → brave its tombs → not enough → solvent → Endera. Für später fünf Endera Herbs notieren.',
 'Auf allen Reisen Wildkräuter aufnehmen. Insgesamt 25 Wildkräuter geben +2 Lady-Punkte für den späteren Drill-Shot-Kauf.',
 {id:'prepare-cemetery-check',text:'Gash und Feast sind jetzt deine ersten beiden Gaben. Mit Shortbow, passenden Pfeilen und Dagger als Nahkampfreserve nach Yarrow zurück; Longbow und Lifesight brauchst du für diesen frühen Versuch nicht abzuwarten. Leichte Startausrüstung behalten und Gesundheit, Poise, Energie sowie Heilreserve auffüllen.'},
 {id:'yarrow-2',text:'Mit Graveyard Key zum Familienfriedhof nördlich der Farm in Yarrow und die Höhle abschließen. Gegner einzeln bekämpfen und bei sinkender Poise Abstand nehmen. Master Key und Black Eyed Stone aus der Haupttruhe nehmen, dann hinaus. Den Stein behalten und seine Inschrift erfragen.'},
 ...stoneInquiry
],['feast'],'Longbow ab PER 10 (5.000); ein Zwischenkauf ist keine Pflicht. Shortbow weiter benutzen, wenn Pfeile und Heilung sonst unbezahlbar werden. Longbow + Dagger + Startkleidung: Last 30 / 40; mit Buckler schon 40, deshalb keine weitere Last ergänzen.','DialogueData.csv:51–59,131–148,363–380,422–425; achievements.lua:45–51; ObjectData.csv; research-cemetery.md','Ein bis zwei Gaben sind unsere Orientierung für die frühe Höhle, kein garantierter Sieg. Der Eingang bleibt bis zum Master Key gesperrt. Feast hilft nur gegen geeignete Gegner; Heiltränke behalten.'),
s('hearth','Hearthaven','Städtereise','Nach der Hauptstadtspur zum Stein über die Straßen nordwärts ins Gebirge nach Hearthaven.',[
 'Hearthaven besuchen: +2 Angels-Devotion. Lifesight als dritten Kauf lernen.',
 'Priest of the Blind Angels: Relic → Tower of Veils → no way in. Die Spur red cloak notieren.',
 hearthavenLore
],['lifesight'],'Dagger als leichte Reserve behalten. Mace wäre ab END 5 anlegbar (1.000), aber Longbow + Mace + Startkleidung + Gloves + Buckler wiegen 50 / 50,71. Als Standard bis END 10 warten; zuerst nur einen bezahlbaren Slot verbessern.','DialogueData.csv:175–177; ObjectData.csv; HearthavenTriggers.csv; strings.lua:138–159; research-secrets.md'),
s('winter','Wintersholl','Städtereise','Zurück Richtung Yarrow, dann ostwärts nach Wintersholl.',[
 'Priester: Garden → not far → the beast → hunting grounds. Die Ziele markieren lassen.',
 'Bewohner nach red cloak fragen: die Tower-Schlüsselspur führt nach Harrowdus.',
 'Klagenden Bewohner: disgrace → rogue guardian → history → weapon → pirates → coast. Die besondere Waffe für Sleathen notieren.'
],[],'Hier keine STR-Waffe für diesen Build kaufen. Bögen aus Hauptstadt/Red Grove behalten; die Wolf-Punkte vom Besuch vorerst liegen lassen.','DialogueData.csv:198–220')
]),
s('harrow','Harrowdus','Städtereise','Von Wintersholl südwärts über die Straßen nach Harrowdus.',[
 'Den Bewohner mit der Begrüßung „Not seen you around before. Dying or killing?“ ansprechen; sein Name ist zufällig. Nacheinander nach furtive → Here → Although fragen. Er schickt dich nach Barrow-Linn, wo du später nach triangular key fragst. Die Pfeile sind Gesprächsthemen, keine Gegenstände, die du hier finden musst.',
 'Priester: Relic → die → insist → phrase. Die Jest-Zugangsphrase als Rätsel aufnehmen.',
 'Sprechende Gans: secrets → Bael\'s Key → Idiot → However.',
 'Vom südlichen Ausgang des Tempels im Norden der Stadt nach rechts (Osten) gehen. Dort stehen zwei kleine Häuser nebeneinander: Das weiter rechts gelegene Haus hat die gesuchte verschlossene Tür an der Südseite. Mit Lockpick öffnen; drinnen liegen Knochen neben einem Bett. Das Fass durchsuchen und die Notiz lesen. Den dort genannten Espirus nach literature → click-clack gang → hideout fragen. „Lockpick breaks!“ bedeutet einen gescheiterten Zufallsversuch; bei „Cannot unlock!“ braucht die Tür einen besonderen Schlüssel.'
],[],'Einige Lockpicks beim Ironmonger (Basis 200), Oil und Heilung beim Apothecary. Vor der nächsten Stadt auffüllen: Barrow-Linn hat keinen Apothecary.','DialogueData.csv:243–248,263–287; HarrowdusTriggers.csv:21; village_sim.lua:53'),
s('barrow','Barrow-Linn','Städtereise','Zur Hauptstadt zurück, die Fähre südwestwärts nehmen; vom Fährort nordwestlich nach Barrow-Linn.',[
 'Priester: Relic → Repository → unlikely → Locus Box → functioning → parts → Roche → still lives.',
 'Bewohner nach triangular key → Funny fragen. Flimpy: fence → guess. Die Spur führt zu Kenner in The Red Grove.',
 'In der Ancestors\' Ossuary die falsche Wand finden und Bael\'s Key nehmen. Für die mögliche alternative Schlussroute behalten.',
 'Prüfen: alle fünf Gottstädte besucht. Das gibt +2 Angels-Punkte; Barrow-Linn selbst gibt +2 Dust-Punkte.'
],w?['blind-leap','revelation']:[],'Vorher gekaufte Heilung behalten. Waffen und Rüstung gibt es hier, Heiltränke jedoch nicht regulär bei einem Apothecary.','DialogueData.csv:316–340; ancestorsTriggers.csv:4; achievements.lua:32–39,56–65'),
s('prepare','Spuren verbinden','Vor dem ersten Relikt','The Red Grove erneut besuchen, dann nach Moon-upon-Thoss zurückkehren.',[
 'In The Red Grove: stranger → Kenner → fled → Moon-upon-Thoss. In der Hauptstadt Bewohner nach Kenner fragen, bis Thief\'s Hideout markiert wird.',
 {id:'prepare-2',text:w?'Nächste Käufe vorbereiten: Hallow, dann Retribution. Hallow kann bis zu den Garden-Belohnungen warten; die erste gesparte Tear ergänzt Angels für Retribution.':'Mit 2 zusätzlichen Lady-Punkten Drill Shot lernen; danach Blind Leap und Revelation. Kräuteraufgabe oder tatsächlich gewonnene Tears nutzen.'},
 {id:'prepare-3',text:'Heilung, passende Munition, Hotkeys und aktuelle Last prüfen. Lange Reliktdungeons erst vorbereitet betreten.'}
],w?['hallow','retribution']:['drill-shot','blind-leap','revelation'],w?'Sword + Schild behalten. Bei END 10 Greaves und Heater einzeln nach Lastprüfung ergänzen; volles Lederset + Sword + Heater + Amulett wiegen 56 / 61,43. Mit vorhandener Fernwaffe leichtere Rüstung oder Buckler behalten: Shortbow ergänzt 10, Crossbow 16. Das volle 56er-Set plus Shortbow erst bei END 15 tragen; Hurl kann die Fernwaffe ersetzen.':'Longbow nur bei Restgold; Dagger bleibt eine leichte Reserve. Mace ist optional. Bei END 10 passt mit Mace zunächst Lederkörper plus Starthelm/-beine; volles Lederset + Round Shield erst bei END 15.','world_data.lua:87; dungeon_data.lua:664–707; treasure_sets.lua:767–770; DialogueData.csv:57–59,148,385–394,504,507; achievements.lua; research-cemetery.md','Punkte sind keine automatische Questbelohnung. Fehlende Gaben verzögern den Kauf, nicht deine ganze Reise. Falls die Yarrow-Höhle oder die Hauptstadtspur zum Stein noch offen ist, die Aufgaben aus Etappe 3 nachholen und den Black Eyed Stone behalten.','Tears aus Rätselorten sind optional. Erst den jeweiligen Ort unterwegs entdecken und seinen Hinweis bestätigen; die Dungeonübersicht ordnet alle zehn Prüfungen ein. Rätsel lösen UND den Wächter besiegen. Spektrale Ritter können sehr gefährlich sein: diese Route plant die Prüfungen später ein, nach dem ersten Relikt.'),
s('hold','The Hold','Erstes Relikt','Von Wintersholl zur südwestlichen Küste. The Hold liegt nahe Fieracarr.',[
 'The Hold abschließen und die garantierte Tooth of Sleathen aus dem Endschatz nehmen.',
 'Zur Stadt zurückkehren, Heilung auffüllen und die besondere Waffe für den nächsten Kampf bereithalten.'
],[],'Tooth of Sleathen ist ein Fund, kein Ladenkauf. Nicht mit The Hole verwechseln – das ist ein anderer Dungeon.','world_data.lua:110; dungeon_data.lua:525–553; treasure_sets.lua:883–886'),
s('garden','Sleathen & Garden','Erstes Relikt','Sleathens Wald liegt nordwestlich Wintersholl; Garden of Lorelei liegt nördlich der Stadt.',[
 'Tooth of Sleathen wirklich als Nahkampfwaffe ausrüsten, dann Sleathen besiegen und Sleathen\'s Head einsammeln. Keine Attributanforderung, einhändig, Last 10: Schild behalten; beim Wechsel von Dagger (Last 4) die zusätzliche Last prüfen.',
 'Mit dem Kopf Garden of Lorelei öffnen. Sieben Etagen und Lord of Trees bewältigen; Steadfast Hand und Endtruhe nehmen.',
 'Lightning-bolt Amulet anlegen: bei 100 Basisenergie auf 120 maximale Energie kommen. Die zusätzliche Halslast 1 prüfen.',
 w?'Howl als neunten Kauf erst lernen, wenn auch die vorherigen Gaben und 5 freie Wolf-Punkte vorhanden sind.':'Moonlight als siebten Kauf erst lernen, wenn auch die vorherigen Gaben und 5 freie Lady-Punkte vorhanden sind.'
],w?['howl']:['moonlight'], 'Lightning-bolt Amulet ist hier beim ersten Abschluss garantiert. Für neutrale Beschwörungen vorerst dieses Amulett tragen.','ActorData.csv:175; world_data.lua:148–154; treasure_sets.lua:773–779','Sleathen ist auch für den Bogen-Build ein besonderer Nahkampf. Slam, Feast und Retribution umgehen seine spezielle Waffenregel nicht.','Vor einem siebenstöckigen Reliktdungeon die Warnung des Spiels beachten: kein einfacher Rückzug durch den Eingang wie in einem Außenareal.'),
s('ship','Schiff & Sea Cave','Weitere Relikte','Harrowdus → südwestliches Click Clack Hideout; danach zum Schiff bei Moon-upon-Thoss.',[
 'Im Click Clack Hideout die Assassinen einzeln bekämpfen, dann den Leader. Mit seinem Schlüssel die Truhe öffnen: Forged Ship Title nehmen.',
 'Zum Schiff neben Moon-upon-Thoss gehen und den Titel nutzen. Die Kaufalternative kostet ungefähr 100.000 Basisgold und ist für diese Route unnötig.',
 'Mit dem Schiff die Sea Cave südlich der Hauptstadt abschließen. Advanced Cannon mitnehmen.'
],[], 'Heilung und Pfeile vor dem Hideout ergänzen. Den erkämpften Forged Ship Title nutzen; Advanced Cannon ist ein Dungeonfund.','ClickclackTriggers.csv:2–12; treasure_sets.lua:863–869; help.lua:60–67'),
s('tower','Tower of Veils','Weitere Relikte','Kennerinsel nordöstlich Wintersholl, südöstlich des großen Meereskreuzes; danach Tower südwestlich Hearthaven.',[
 'Thief\'s Hideout auf der markierten Kennerinsel anfahren und besiegen. Tower Keys nehmen.',
 'Tower of Veils mit den Schlüsseln öffnen und abschließen. All-seeing Eye und Amulet of Wintertree aus dem Endschatz mitnehmen.'
],w?['shockwave']:['retribution'],'Wintertree-Amulett als Feuerabwehr merken. Ein Wechsel ersetzt das Energie-Amulett: neutrale Beschwörungen brauchen weiterhin max. 120 Energie.','OverworldTriggers.csv:93,126; treasure_sets.lua:806–812','Die hier vorgeschlagenen späten Gaben erst kaufen, wenn ihre vorherigen Käufe und Punkte vorhanden sind.','Boss-Hilfe: Almas\' Dunkelheit und Schild über alle vier Braziers auflösen. In der Dunkelheit keine Schläge auf das Schild verschwenden.'),
s('jest','Jest','Weitere Relikte','In Harrowdus in den Grocer-Rückraum; hinter der falschen Wand liegt der Eingang.',[
 'Die fünf Wörter und die Rätselnotiz des Priesters zusammentragen. Unter „Geheimnisse“ nur tatsächlich gefundene Hinweise bestätigen; die Zugangslösung wird erst mit allen Hinweisen freigegeben.',
 'Die vollständige Phrase in Eingangsnähe rufen. Sieben Etagen abschließen; Trickster\'s Mask und Heart-shaped Amulet nehmen.'
],w?[]:['star-shot'],'Feuer-/Statusreserve und genügend Munition. Bei Wintertree-Wechsel Energiegrenze neu prüfen. Star Shot braucht 8 Pfeile/Bolzen pro Einsatz.','strings.lua:83–86; HarrowdusTriggers.csv:11; actor_boss.lua:945–1072',undefined,'Boss: „says“ bedeutet befolgen; „laughs“ bedeutet das Gegenteil. Nicht pauschal alles umkehren. Die Zugangslösung steht unter „Geheimnisse“ erst nach Bestätigung aller Hinweise bereit.'),
s('necropolis','Necropolis','Weitere Relikte','In Harrowdus fehlende Kräuterfundorte erfahren und die Karten tatsächlich lesen. Erst bestätigten Ortsinformationen folgen. Sobald du fünf Endera Herbs hast, zur Handmaiden in The Red Grove zurückkehren.',[
 'Falls du die Fundorte noch nicht kennst: Beim Ironmonger (Hardware Store) im Südwesten von Harrowdus Treasure Map #6 und #8 kaufen, jeweils Basis 2.000. Nur benötigte Karten kaufen. Auf Land: I → Karte auswählen → Enter → Read bestätigen; dann der neuen Weltkartenmarkierung folgen. Kräuterorte heißen anfangs „a secret location“ / „???“.',
 'Fünf Endera Herbs an bereits bekannten Fundorten sammeln. Die Karten und Ortsinformationen unter „Dungeonhinweise & Besuche“ einzeln bestätigen; nur danach dem jeweiligen Marker folgen. Im Zentrum der Vier-Stein-Gruppen in die Lokalansicht wechseln und Kräuter aufnehmen. Bei fünf aufhören: weder alle Karten noch Meida\'s Hideout sind Pflicht.',
 'Mit fünf Kräutern zur Handmaiden zurück: brew. Witches\' Solvent bekommen; der Kauf für Basis 400.000 ist kein Anfängerziel.',
 'Solvent am Necropolis-Zugang südöstlich The Red Grove verwenden. Sieben Etagen abschließen und Crimson Candle samt Endschatz nehmen.'
],[], 'Oil gegen Rot und passende Heilung. Karten sind Orientierungshilfen, kein Pflichtkauf. Kräuter aufnehmen und Geistern ausweichen; nicht jeden optionalen Kampf erzwingen.','ObjectData.csv:389–398,403; state_game.lua:22527–22533; speech_area.lua:18,2096–2100; witches_herb_Triggers.csv; DialogueData.csv:379', 'Fünf Kräuter sind erforderlich, nicht fünf getrennte Schreine. Bestand im Inventar zählen; ausgelassene Quellen sind kein Rückstand.','Weitere Kräuterquellen findest du unter „Dungeons“ bei den Treasure Maps #6–#10. Karten beim Harrowdus-Ironmonger kaufen und tatsächlich lesen oder den Ort selbst im Spiel entdecken. Erst nach bestätigtem Hinweis erscheint der jeweilige Weg. Die vier Steingruppen enthalten mehrere einzelne Herbs; Meida ist ein Dungeon mit eingeschränktem Rückzug und keine Abkürzung zu fünf Herbs. Bei fünf Pflanzen zur Handmaiden zurückkehren; weitere Quellen sind optional.'),
s('repository','Repository','Letztes Relikt','Empfohlener Sammelkurs: Harrowdus → Enflamed Glade → Venom Cube → Poison Cross → Bael\'s Tomb → Magma Chamber per Schiff. Danach Runacarr bei der Hauptstadt.',[
 'Fehlende Orte markieren: beim Ironmonger im Südwesten von Harrowdus nur die benötigten Treasure Maps #1–#5 kaufen (Basis je 2.000). Auf Land mit I → Karte → Enter → Read lesen, dann den Weltkartenmarker verfolgen. Gelesene Karten werden verbraucht; die Markierung bleibt.',
 'Enflamed Glade: Map #4. Südwestlich Wintersholl und nördlich Harrowdus, direkt östlich der Map-#8-Kräutergruppe. Per Schiff am Steg unmittelbar nördlich anlegen, dann südwärts zur Ruine. In Lokalansicht Feuerfallen beachten und Fragment aus dem Container nehmen.',
 'Venom Cube: Map #2. Nordwestlich Wintersholl, nordöstlich Yarrow, im Inneren der großen ringförmigen Waldregion. Dem Marker folgen, Lokalansicht betreten und Fragment aus dem Container nehmen; Giftfallen und Gegner beachten.',
 'Poison Cross: Map #1. Südöstlich The Red Grove und westlich Meida\'s Hideout. Vom südlichen Red-Grove-Ausgang dem Weg ost-/südostwärts durch den Berg-/Flussdurchgang über die Brücken folgen; die Ruine liegt zuletzt nördlich des Weges. Fragment aus dem Container nehmen; Giftfallen beachten.',
 'Bael\'s Tomb: Map #3. Deutlich südlich The Red Grove, etwas westlicher als die Stadt; südöstlich Essacarr Henge. Den südlichen Weg über die Brücken verfolgen. Die Außenruine führt in einen Dungeon: vorbereitet abschließen und Fragment aus dem Hauptschatz nehmen. Dies ist nicht Bael\'s Key aus Barrow-Linn.',
 'Magma Chamber: Map #5. Mit dem Schiff zur äußersten Südküste, südlich Moon-upon-Thoss und südwestlich Harrowdus. Am Steg an der Südseite der kleinen Landstelle anlegen, wenige Felder nordwärts zur Ruine. Amberfallen und Turrets beachten; Fragment aus dem Container nehmen.',
 'Mit fünf Fragmenten entsteht automatisch Locus Box. An Runacarr benutzen, um Thossacarr sichtbar zu machen.',
 'Über die Nordverbindung des Henges auf die Insel; vom Insel-Henge nordöstlich zum Repository. Dungeon abschließen; Pale Heart und Vermier\'s Amulet nehmen.'
],[], 'Magma Chamber braucht das Schiff. Heilung, Statusmittel und Fernangriff vorbereiten; Water gegen Feuer für Enflamed Glade. Karten nur für fehlende Orte kaufen; gegen Maschinen optional Sabotage erwägen.','ObjectData.csv:389–393; world_data.lua:66–70; state_game.lua:22502–22533; OverworldTriggers.csv; treasure_sets.lua:799–805,871–875','Hengeziele wirklich besuchen/sehen; nur eine Kartenmarkierung genügt nicht. Vor Bael\'s Tomb und Repository volle Reserven.','Sekundäre Rechercheanker: Poison Cross (217,204), Venom Cube (306,219), Bael\'s Tomb (173,228), Enflamed Glade (313,268), Magma Chamber (267,412). Folge den Kartenmarkern statt einer ungeprüften geraden Linie durch Berg oder Meer. Lens Keeper: zuerst Shield Crystals zerstören; nach Phasenwechsel erneut.'),
s('egg','The Egg · DX','Vor dem Abschluss','Mit dem Schiff von Barrow-Linn südwestwärts zur weit westlichen, bergigen Küstenbucht. Von der Meeresseite an den nach Osten zeigenden Steg anlegen; an Land sechs Weltkacheln westwärts durch das Gehölz zum großen Ei.',[
 'Nach den fünf Relikten die nummerierte Gabenliste und das späte END-15-Set fertigstellen. In einer Stadt gesund, mit voller Energie, Nahrung und Reserven starten. The Egg jetzt einschieben, bevor du eine der Schlussrouten beginnst.',
 'Den Anleger und das Ei erreichen. Sekundäre Kartenanker: Steg (120,341), Ei (114,341), deutlich südwestlich Barrow-Linn. Kein gerader Landweg durch die umliegenden Berge.',
 'Das große Ei anrempeln; danach auf den geöffneten Eingang gehen und Enter drücken. Die Einwegwarnung erst bestätigen, wenn du für den langen Dungeon bereit bist. Bei „Dee Ell See“ die DLC-Installation in Steam prüfen.',
 'Den Lauf bis Etage 100 abschließen, den Preis aufnehmen und durch den dortigen Ausgang wieder an die Oberfläche zurückkehren. Danach in einer Stadt auffüllen und erst dann den Abschluss wählen.'
],[],w?'Sword + Heater Shield, leichtes Lederset + Garden-Amulett: 56 Last. Hurl als Distanzhilfe; optionaler Shortbow ergänzt 10 auf 66 / 72,14 bei END 15. Heil-/Statusmittel, Nahrung, Water und Energieversorgung auffüllen.':'Longbow + Mace + Round Shield, leichtes Lederset; das bisherige 68/72,14-Set behalten. Pfeile, Heil-/Statusmittel, Nahrung, Water und Energieversorgung auffüllen.','OverworldTriggers.csv:205,384; Overworld.png; actor.lua:4213–4234; state_game.lua:11463–11495; world_data.lua:205–314; research-egg.md','DX ist Zusatzinhalt; für diese Route ist es eingeplant. Zugang hat kein Relikt-Gate, die späte Einordnung ist unsere Vorbereitungsempfehlung. Auf Etage 1 gibt es keinen Rückweg nach draußen. Neutral Howl/Moonlight nur mit aktuell mindestens 120 maximaler Energie benutzen.')
];
}
export const eggFloorIds=Array.from({length:100},(_,i)=>`egg-floor-${i+1}`);
export const eggBands=[
 {enemies:'Hive, Käfer, Fledermäuse, Spinnen, Wölfe und erste humanoide Gruppen. Minibosse können Dire Wolf, Hunter oder Spectral Knight sein.',tip:'Die normale Kampfroutine trägt den Lauf. Früh prüfen, ob du Energie und Heilung zuverlässig einteilen kannst.'},
 {enemies:'Stärkere Varianten der frühen Gruppen; Dolls werden möglich.',tip:'Vor unbekannten Türen deine Stellung und freie Rückzugsfelder sichern.'},
 {enemies:'Ghost Bats, Rotlings und Light Spectres; Gazer werden als Minibosse möglich.',tip:'Rot- und Blindheitsmittel für später behalten. Die ersten leichten Etagen sind keine Zusage für den Rest.'},
 {enemies:'Silverwolves, Amberghasts und stärkere Untote; Reaper und Death-Maidens werden möglich.',tip:'Sichtlinien und Status im Blick behalten. Ab Etage 34 können Bell-Räume bis zu zwei Bells vorsehen.'},
 {enemies:'Forgotten Hulks, Hunters, Creepers, Boggarts und Mimics; Darknight wird als Miniboss möglich.',tip:'Räume und Truhen bewusst sichern. Ein vollständiges Leerräumen jeder Etage ist kein Pflichtziel.'},
 {enemies:'Bug Eyes, Ghosts und Blindwolves; Great Gazer wird als Miniboss möglich.',tip:'Lifesight vor verdeckten Begegnungen nutzen. Keine sichere Auffüllung durch zufällige Beute erwarten.'},
 {enemies:'Borog, Techs, Impalers und Shimmershee; mechanische Gruppen werden möglich.',tip:'Feast bleibt ein Gelegenheitswerkzeug. Unabhängige Heilung aufheben; ab Etage 67 sind bis zu drei Bells vorgesehen.'},
 {enemies:'Zusätzlich Constructs, Spikers, Bombers und Dice.',tip:'Freie Bewegungsfelder und einen normalen Fernangriff bewahren. Teure Gaben gezielt einsetzen.'},
 {enemies:'Stärkere Techs/Constructs, Firewalkers und Piercers.',tip:'Feuer- und Statusreserven vor weiterem Abstieg prüfen. Lebensmittel ersetzen keine HP-Heilung.'},
 {enemies:'Auf 91–99 stärkste Gruppen, einschließlich Dark Spectres. Reaper, Darknight und Great Gazer im Miniboss-Pool; 100 ist eine feste Abschlusskarte.',tip:'Auf 99 vor dem Abstieg heilen, Status bereinigen und Energie, Munition sowie Amulett prüfen. Von Etage 100 führt keine normale Treppe zurück zu 99.'}
];
export function eggFloorMarkers(n:number){
 if(n===100)return 'Feste Abschlusskarte · Hilfe unten eingeklappt';
 const tags:string[]=[];
 if(n%4===3)tags.push('Maiden möglich');
 if(n%4===0)tags.push(`Bells vorgesehen (bis ${n<=33?1:n<=66?2:3})`);
 if(n%7===6)tags.push('Library vorgesehen');
 if(n===34||n===67)tags.push('Mehr Bells ab diesem Band');
 if(n===99)tags.push('Vor Abstieg zu 100 vorbereiten');
 return tags.join(' · ')||'Abstieg, nötige Schlüssel, Reserven';
}
export const equipment:Record<BuildId,{phase:string;items:string;load:string;note:string}[]> = {
 wolf:[
 {phase:'Start · END 0',items:'Dagger 4 + Cap 1 + Cotton Tunic 8 + Leggings 1',load:'14 / 40',note:'Bereits vorhanden, kein Kauf. Die ausgerüsteten Startsteine haben Gewicht 0.'},
 {phase:'Slam · STR 5, END 0',items:'Shortsword 10 + Cap 1 + Cotton Tunic 8 + Leggings 1 + Buckler 10',load:'30 / 40',note:'Nur Waffe und Schild gekauft. Dagger bleibt im Inventar; Handschuhe und Cloak sind keine Voraussetzung.'},
 {phase:'Optionale frühe Jagd · STR 5, END 0',items:'Shortsword 10 + Cap 1 + Cotton Tunic 8 + Leggings 1 + Crossbow 16',load:'36 / 40',note:'Buckler für die Jagd ablegen; sonst 46 / 40. Mit Dagger statt Shortsword und Buckler wären es 40 / 40. Crossbow und Bolts nur bei echtem Bedarf kaufen.'},
 {phase:'Hurl · STR 10, END 0',items:'Sword 12 + Cap 1 + Cotton Tunic 8 + Leggings 1 + Buckler 10',load:'32 / 40',note:'Sword ersetzt Shortsword oder direkt Dagger. Leather Gloves würden 2 Last ergänzen, sind aber optional.'},
 {phase:'Lifesight · STR 10, END 5',items:'Sword 12 + Cap 1 + Leather Armour 15 + Leggings 1 + Buckler 10',load:'39 / 50,71',note:'Ein einzelner Körperkauf statt eines ganzen Ledersets. Mit Leather Gloves: 41; danach Leather Helmet statt Cap: 44. Beine noch behalten.'},
 {phase:'Blind Leap · STR 10, END 10',items:'Sword 12 + Lederkörper/-handschuhe/-beine/-helm 27 + Heater Shield 16 + Lightning-bolt Amulet 1',load:'56 / 61,43',note:'Greaves und Heater einzeln ergänzen, Amulett nur nach Fund. Ohne Amulett 55; Shortbow zusätzlich wäre 66 und damit über der Grenze.'},
 {phase:'Retribution · STR 10, PER 5, END 15',items:'Voriges 56er-Set + optional Shortbow 10',load:'66 / 72,14',note:'Shortbow erst mit PER 5, z. B. nach Feast. Ohne Bogen bei 56 bleiben. Woolen Cloak zusätzlich: 70; mehr Last kostet Bewegung und Dodge.'}
 ],
 lady:[
 {phase:'Start · END 0',items:'Dagger 4 + Cap 1 + Cotton Tunic 8 + Leggings 1',load:'14 / 40',note:'Bereits vorhanden, kein Kauf. Die ausgerüsteten Startsteine haben Gewicht 0.'},
 {phase:'Gash · PER 5, END 0',items:'Shortbow 10 + Dagger 4 + Cap 1 + Cotton Tunic 8 + Leggings 1',load:'24 / 40',note:'Zuerst Bogen und Pfeile. Optional Buckler: 34. Kein Cloak- oder Rüstungskauf nötig.'},
 {phase:'Feast · PER 10, END 0',items:'Longbow 16 + Dagger 4 + Cap 1 + Cotton Tunic 8 + Leggings 1',load:'30 / 40',note:'Nur bei genug Gold; Shortbow bleibt brauchbar. Mit Buckler bereits 40: keine Handschuhe oder Cloak zusätzlich anlegen.'},
 {phase:'Lifesight · PER 10, END 5',items:'Longbow 16 + Dagger 4 + Cap 1 + Cotton Tunic 8 + Leggings 1 + Leather Gloves 2 + Buckler 10',load:'42 / 50,71',note:'Dagger weiter nutzen. Mace statt Dagger wäre 50: technisch passend, aber fast voll und mit Stealth −1. Für mehr Beweglichkeit den Kauf bis END 10 verschieben.'},
 {phase:'Blind Leap · PER 10, END 10',items:'Longbow 16 + Mace 12 + Cotton Tunic 8 + Cap 1 + Leather Gloves 2 + Leggings 1 + Buckler 10 + Lightning-bolt Amulet 1',load:'51 / 61,43',note:'Mace erst ab END 5, Amulett nur nach Fund. Leather Armour statt Tunic ergänzt 7: dann 58. Ohne Amulett jeweils 1 weniger.'},
 {phase:'Retribution · PER 10, END 15',items:'Longbow 16 + Mace 12 + Lederkörper/-handschuhe/-beine/-helm 27 + Round Shield 12 + Lightning-bolt Amulet 1',load:'68 / 72,14',note:'Helmet, Greaves und Round Shield einzeln ersetzen. Mit Dagger statt Mace nur 60. Cloak würde 72 ergeben; die freie Reserve lieber behalten.'}
 ]
};
export interface ShoppingStep { item:string; price:string; where:string; requirement:string; action:string; load:string; skip:string }
export const shoppingSteps:Record<BuildId,ShoppingStep[]> = {
 wolf:[
 {item:'Buckler: ein günstiger Anfang',price:'100',where:'Armourer · alle sechs Städte',requirement:'Keine Stat-Schwelle · Gewicht 10',action:'Nach der Heilreserve als ersten kleinen Kauf ergänzen. Cap, Cotton Tunic und Leggings behalten.',load:'Startset 14 + Buckler 10 = 24 / 40 bei END 0.',skip:'Bereits einen geeigneten Schild gefunden? Kauf auslassen. Heater direkt ist erlaubt, wenn 800 Gold nach der Reserve übrig bleiben und die aktuelle Last passt; dafür nicht den ersten Waffenkauf opfern.'},
 {item:'Dagger durch Shortsword oder direkt Sword ersetzen',price:'Shortsword 1.000 · Sword 2.000',where:'Weaponsmith · Shortsword überall, Sword nur Wintersholl',requirement:'Shortsword STR 5 · Sword STR 10 · Gewicht 10 / 12',action:'Nach Slam ist Shortsword anlegbar. Es hilft sofort, wenn du mit Dagger Probleme hast. Nach Hurl ist Sword anlegbar; bei STR 10 und genug Restgold direkt Sword kaufen.',load:'Mit Startkleidung und Buckler: Shortsword 30 / 40; Sword 32 / 40. Der alte Dagger wird ersetzt.',skip:'Du musst nicht beide kaufen. Dagger → Sword spart den Shortsword-Kauf, wenn du die Zwischenzeit sicher schaffst. Einen bereits gekauften Shortsword weiter benutzen, bis Sword bezahlbar ist; gleichwertige Beute ersetzt beide Käufe.'},
 {item:'Leather Gloves für den freien Handslot',price:'300',where:'Armourer · alle sechs Städte',requirement:'Keine Stat-Schwelle · Gewicht 2',action:'Erst nach brauchbarer Hauptwaffe und Heilreserve kaufen, wenn Geld übrig ist. Deine vier Startteile bleiben sonst erhalten.',load:'Sword + Startkleidung + Buckler: 32 → 34 / 40 bei END 0.',skip:'Bei knappem Gold verschieben. Ohne Handschuhe lässt sich der Weg fortsetzen; die folgenden Zahlen enthalten sie nur als Rechenbeispiel.'},
 {item:'Cotton Tunic durch Leather Armour ersetzen',price:'800',where:'Armourer · alle sechs Städte',requirement:'Keine Stat-Schwelle · empfohlen ab Lifesight / END 5',action:'Nur das Körperteil ersetzen, kein ganzes Lederset kaufen. Gewicht 8 → 15, Stealth −1. Bei knappem Geld die Cotton Tunic weiter tragen.',load:'Mit Sword, Buckler, Cap, Leggings und Gloves: 34 − 8 + 15 = 41 / 50,71 bei END 5.',skip:'Mit anderer Kombination kann Leder auch früher passen. Entscheidend ist die tatsächliche Gesamtlast; END 5 ist unsere Empfehlung, keine Anlegesperre.'},
 {item:'Cap durch Leather Helmet ersetzen',price:'400',where:'Armourer · alle sechs Städte',requirement:'Keine Stat-Schwelle · Gewicht 1 → 4',action:'Als nächsten einzelnen Rüstungskauf erwägen. Leggings bleiben an; Steel Helmet zunächst auslassen.',load:'Voriges 41er-Set: 41 − 1 + 4 = 44 / 50,71 bei END 5.',skip:'Cap ist bereits vorhanden und wird nicht erneut gekauft. Bei anderem Schild oder zusätzlicher Waffe erst die neue Last prüfen.'},
 {item:'Leggings durch Leather Greaves ersetzen',price:'600',where:'Armourer · alle sechs Städte',requirement:'Keine Stat-Schwelle · empfohlen ab Blind Leap / END 10',action:'Gewicht 1 → 6. Für etwas mehr Beinschutz zahlst du 600 und trägst 5 mehr; deshalb darf dieser Schritt warten.',load:'Voriges 44er-Set: 44 − 1 + 6 = 49 / 61,43 bei END 10.',skip:'Bei END 5 wären 49 / 50,71 schon fast voll. Leggings behalten, wenn dir Beweglichkeit oder Gold wichtiger sind.'},
 {item:'Buckler durch Heater Shield ersetzen',price:'800',where:'Armourer · alle sechs Städte',requirement:'Keine Stat-Schwelle · Gewicht 10 → 16',action:'25% statt 10% Basis-Blockchance, aber 6 mehr Last und Stealth −1. Als einzelnen Kauf durchführen; bei wenig Gold Buckler behalten.',load:'Voriges 49er-Set: 49 − 10 + 16 = 55 / 61,43 bei END 10. Garden-Amulett nach Fund: 56.',skip:'Mit leichterer Kleidung darf Heater früher kommen. Beispiel Sword + Startkleidung + Gloves + Heater: 40. Hast du Heater schon, Buckler auslassen; Kite ist keine Pflicht.'},
 {item:'Fernwaffe für Jagd oder regelmäßige Distanzangriffe',price:'Shortbow oder Crossbow jeweils 1.000 · Munition extra',where:'Weaponsmith · Shortbow Hauptstadt/Red Grove; Crossbow Hauptstadt/Wintersholl',requirement:'Shortbow PER 5 nach Feast, Gewicht 10 · normale Crossbow STR 5 nach Slam, Gewicht 16',action:'Diesen optionalen Kauf schon in Etappe 3 vorziehen, wenn dir Hirsche entkommen: Crossbow + Bolts hilft vor Hurl. Nach Feast ist der leichtere Shortbow + Arrows eine Alternative. Eine vorhandene Fernwaffe weiter benutzen; nicht beide kaufen müssen. Hurl kann den Kauf später ersetzen.',load:'Frühe Crossbow mit Shortsword + Startkleidung ohne Buckler: 36 / 40; mit Buckler 46 und zu schwer. Shortbow + Sword + Startkleidung + Buckler: 42 / 50,71 bei END 5. Volles 56er-Lederset erst bei END 15: Shortbow 66, Crossbow 72 / 72,14.',skip:'Fehlen Gold, passende Attribute oder Lastreserve, die Hirschjagd verschieben. END 15 ist nur für das volle schwere Vergleichsset nötig. Für eine frühe Jagd auf Rüstungskäufe verzichten und gegebenenfalls den Buckler ablegen.'}
 ],
 lady:[
 {item:'Shortbow oder direkt Longbow kaufen',price:'Shortbow 1.000 · Longbow 5.000 · Pfeile extra',where:'Weaponsmith · Shortbow Hauptstadt/Red Grove; Longbow nur Red Grove',requirement:'Shortbow PER 5 · Longbow PER 10 · Gewicht 10 / 16',action:'Nach Gash ist Shortbow anlegbar. Dagger als Nahkampfreserve und die Startkleidung behalten. Nach Feast darfst du direkt Longbow kaufen, falls danach noch Pfeile und Heilung bezahlbar sind.',load:'Mit Dagger und Startkleidung: Shortbow 24 / 40; Longbow 30 / 40 bei END 0.',skip:'Beide Käufe sind keine Pflicht. Shortbow → Longbow nur bei genug Gold; ein vorhandener Shortbow bleibt brauchbar. Direkt Longbow spart 1.000, wenn du die Zeit ohne Bogen sicher überbrücken kannst.'},
 {item:'Buckler als optionale Nahkampfreserve',price:'100',where:'Armourer · alle sechs Städte',requirement:'Keine Stat-Schwelle · Gewicht 10',action:'Erst nach Bogen, Pfeilen und Heilreserve. Der Schild kostet zusätzliche Last; für mehr Beweglichkeit kannst du den Slot frei lassen.',load:'Mit Startkleidung und Dagger: Shortbow-Set 24 → 34; Longbow-Set 30 → 40 / 40 bei END 0.',skip:'Mit Longbow bei END 0 bleibt keine Lastreserve. Keine Gloves oder Cloak ergänzen. Round Shield direkt kostet 200 und wiegt 12: mit Longbow-Startset 42, deshalb hier erst ab END 5.'},
 {item:'Leather Gloves für den freien Handslot',price:'300',where:'Armourer · alle sechs Städte',requirement:'Keine Stat-Schwelle · Gewicht 2',action:'Mit Longbow und Buckler bis Lifesight / END 5 warten. Cap, Tunic und Leggings besitzt du schon; dafür kein Gold ausgeben.',load:'Longbow + Dagger + Startkleidung + Buckler: 40 → 42 / 50,71 bei END 5.',skip:'Mit Shortbow und Buckler wären Gloves schon bei END 0 möglich: 36 / 40. Bei knappem Gold weiter warten.'},
 {item:'Dagger bei Bedarf durch Mace ersetzen',price:'1.000',where:'Weaponsmith · alle sechs Städte',requirement:'Mace END 5 · Gewicht 4 → 12',action:'Lifesight erfüllt die Anforderung. Mit Longbow bleibt das Set dann aber fast voll; als Standard bis Blind Leap / END 10 den Dagger behalten. Mace hat Stealth −1.',load:'Voriges 42er-Set: 42 − 4 + 12 = 50. Bei END 5 nur 0,71 frei; bei END 10 Kapazität 61,43. Amulett nach Fund: 51.',skip:'Dagger ist anlegbar ohne Stat-Schwelle und bleibt eine leichte Reserve. Mace ist kein Pflichtkauf; für Sleathen brauchst du weiterhin Tooth of Sleathen.'},
 {item:'Cotton Tunic durch Leather Armour ersetzen',price:'800',where:'Armourer · alle sechs Städte',requirement:'Keine Stat-Schwelle · empfohlen ab END 10',action:'Ein einzelner Körperkauf. Gewicht 8 → 15, Stealth −1. Mit der schwereren Mace zuerst die Lastreserve prüfen.',load:'Longbow + Mace + leichte Kleidung + Gloves + Buckler + Amulett: 51 − 8 + 15 = 58 / 61,43 bei END 10.',skip:'Ohne Amulett 57. Mit Dagger statt Mace jeweils 8 weniger: Leder kann dann früher passen. Bei Goldmangel Cotton Tunic behalten.'},
 {item:'Cap durch Pointed Cap oder Leather Helmet ersetzen',price:'Pointed Cap 1.600 · Leather Helmet 400',where:'Pointed Cap: Armourer in Red Grove · Leather Helmet: alle sechs Städte',requirement:'Keine Stat-Schwelle · Gewicht 1 / 4',action:'Für den Bogen ist Pointed Cap das Ziel: +20% phys. Fernkampfschaden und Reichweite +2 ohne zusätzliche Last. Leather Helmet ist die günstigere Schutzalternative. Nur eines der Teile kaufen, nachdem die Versorgung bezahlt ist.',load:'Voriges 58er-Set: mit Pointed Cap weiterhin 58; mit Leather Helmet 58 − 1 + 4 = 61 / 72,14 bei END 15. Die folgenden Beispiele rechnen mit Leather Helmet; mit Pointed Cap jeweils 3 weniger.',skip:'Pointed Cap darf früher kommen, sobald 1.600 plus Versorgungsgold übrig sind. Cap behalten, wenn Gold fehlt; Leather Helmet mit Mace und Lederkörper erst bei genügend Lastreserve.'},
 {item:'Leggings durch Leather Greaves ersetzen',price:'600',where:'Armourer · alle sechs Städte',requirement:'Keine Stat-Schwelle · Gewicht 1 → 6',action:'Als separaten nächsten Kauf durchführen, falls noch Gold nach der Versorgung übrig ist.',load:'Voriges 61er-Set: 61 − 1 + 6 = 66 / 72,14 bei END 15.',skip:'Leggings behalten spart 600 Gold und 5 Last. Kein kompletter Rüstungskauf auf einmal nötig.'},
 {item:'Buckler durch Round Shield ersetzen',price:'200',where:'Armourer · alle sechs Städte',requirement:'Keine Stat-Schwelle · Gewicht 10 → 12',action:'15% statt 10% Basis-Blockchance für 2 mehr Last. Als günstiges spätes Upgrade, wenn du überhaupt einen Schild benutzt.',load:'Voriges 66er-Set: 66 − 10 + 12 = 68 / 72,14 bei END 15.',skip:'Round Shield darf direkt kommen, sobald dein tatsächliches Set genug Platz hat. Buckler dann nicht zusätzlich kaufen. Ohne Schild bleibt der Build leichter.'}
 ]
};
export const finale = [
 {title:'Erster Abschluss',text:'Alle fünf Relikte sammeln: Steadfast Hand, All-seeing Eye, Trickster\'s Mask, Crimson Candle und Pale Heart. Für die DX-Route zuerst The Egg abschließen. Nach Moon-upon-Thoss zum Archon zurückkehren und mit dem Thron interagieren. Das löst das erste Ende aus. Wenn du die alternative Route möchtest, vor der Throninteraktion weiterlesen.'},
 {title:'Roche und die Glocke',text:'Mit Black Eyed Stone zu Hermit\'s Hut auf der Insel nordwestlich Red Grove (Welt 140,172), per Schiff oder bekannter Henge-Verbindung. Gespräch: Roche → lives → Serpents → guardian → nothing → learned much / gods / move on → Tether → true names → too old → shades → free them. Tarthus notieren und Roche\'s Bell nehmen.'},
 {title:'Vier Geister finden',text:'Die Glocke weist zur nächsten offenen Stelle. Auf der Weltkachel in Lokalansicht wechseln und in der Nähe klingeln: Yarrow am Wasser nordwestlich der Farm (lokal 26,43), Weltmeer (224,397), Sumpf südlich Harrowdus (312,333), Kraterrand nördlich Wintersholl (302,80). Geister besiegen und Caryon, Anun, Balatoth, Hezreh erfahren. Wiederholtes Klingeln kann Statusbelastungen verursachen.'},
 {title:'Issacarr öffnen',text:'Bael\'s Key aus der Ossuary in Barrow-Linn am geschützten südlichen Stein in Issacarr, südöstlich Harrowdus (317,319), anwenden. Nostacarr (404,371) wird aktiv. Die Südseite der Henge-Verbindung benutzen: vom Norden zur Warpmitte gehen. Auf der Insel den nächsten Eingang selbst entdecken und unter den Dungeonhinweisen dieser Schlussroute bestätigen, bevor du aufbrichst.'},
 {title:'Vor The Lament',text:'Nach allen fünf Relikten ist dies die empfohlene Fortsetzung; kein zusätzliches Relikt-Gate am Eingang wird behauptet. The Egg vorher abschließen. Alles danach erneut auffüllen: Heilung, Energie, Ammo, Statusmittel. Fünf Arenen und eine sechste Boss-Ebene; der Eingang schließt. Passende normale Ausrüstung genügt als Ziel, keine Legendary-Pflicht.'},
 {title:'Die fünf Altäre',text:'Im Tether-Raum Bodensymbole beachten; Altäre stehen je nach Run unterschiedlich. In Rufreichweite 2 am passenden Altar den Namen rufen: Wolf Tarthus; Harlequin Caryon; Dust Anun; Lady Balatoth; Angels Hezreh. Nach allen fünf erlischt der Schild; dann Tether bekämpfen. Todesblick kann aus Distanz 4 gefährlich werden: Blicklinie vermeiden. Der letzte Altar löst zudem einen Lebens-/Statusangriff auf dich und deine Helfer aus.'},
 {title:'Nach dem finalen Kampf',text:'The Lament verlassen. Dadurch verändert sich die Welt und die göttlichen Gaben, Devotion und Eid werden zurückgesetzt; Attributwerte und normale Ausrüstung bleiben wichtig. Für den Abschluss nach Moon-upon-Thoss zum Archon und mit dem Thron interagieren. Danach keine Kampfroute mehr auf Feast oder Howl aufbauen.'}
];
